# constants.py — shared domain constants
# ZERO imports from other project modules
# NO module-level os.environ reads

# --- Strategy actions ---
STRATEGY_ACTION_NOTHING = "STRATEGY_ACTION_NOTHING"
STRATEGY_ACTION_OPEN_LONG = "STRATEGY_ACTION_OPEN_LONG"
STRATEGY_ACTION_CLOSE_LONG = "STRATEGY_ACTION_CLOSE_LONG"
STRATEGY_ACTION_CLOSE_LONG_PART = "STRATEGY_ACTION_CLOSE_LONG_PART"
STRATEGY_ACTION_OPEN_SHORT = "STRATEGY_ACTION_OPEN_SHORT"
STRATEGY_ACTION_CLOSE_SHORT = "STRATEGY_ACTION_CLOSE_SHORT"
STRATEGY_ACTION_CLOSE_SHORT_PART = "STRATEGY_ACTION_CLOSE_SHORT_PART"
STRATEGY_ACTION_MOVE_STOP_LOSS_LONG = "STRATEGY_ACTION_MOVE_STOP_LOSS_LONG"
STRATEGY_ACTION_MOVE_STOP_LOSS_SHORT = "STRATEGY_ACTION_MOVE_STOP_LOSS_SHORT"
STRATEGY_ACTION_DO_STOP_LOSS = "STRATEGY_ACTION_DO_STOP_LOSS"

# --- Position types ---
POSITION_TYPE_UNKNOWN = "POSITION_TYPE_UNKNOWN"
POSITION_TYPE_LONG = "POSITION_TYPE_LONG"
POSITION_TYPE_SHORT = "POSITION_TYPE_SHORT"

# --- Position states ---
POSITION_STATE_WAIT = "POSITION_STATE_WAIT"
POSITION_STATE_WAIT_BUY = "POSITION_STATE_WAIT_BUY"
POSITION_STATE_WAIT_SELL = "POSITION_STATE_WAIT_SELL"
POSITION_STATE_WAIT_SAFETY_BUY = "POSITION_STATE_WAIT_SAFETY_BUY"
POSITION_STATE_WAIT_SAFETY_SELL = "POSITION_STATE_WAIT_SAFETY_SELL"

# --- Level types (integers) ---
# NOTE: LEVEL_TYPE_SHORT_1_RESISTANCE and LEVEL_TYPE_SHORT_2_RESISTANCE are
# explicitly NOT defined — they have been removed from the domain model.
LEVEL_TYPE_LONG_SUPPORT = 1
LEVEL_TYPE_LONG_RESISTANCE = 2
LEVEL_TYPE_SHORT_SUPPORT = 3
LEVEL_TYPE_SHORT_RESISTANCE = 4
LEVEL_TYPE_TARGET = 5
LEVEL_TYPE_AUTO_SUPPORT = 6
LEVEL_TYPE_AUTO_RESISTANCE = 7

# --- Level dict keys ---
LI_NAME = "LI_NAME"
LI_TIME1 = "LI_TIME1"
LI_VAL1 = "LI_VAL1"
LI_TIME2 = "LI_TIME2"
LI_VAL2 = "LI_VAL2"
LI_ACTIVE = "LI_ACTIVE"
LI_TYPE = "LI_TYPE"
LI_HAD_CONTACT = "LI_HAD_CONTACT"

# --- Trade types ---
TRADE_BUY = "TRADE_BUY"
TRADE_SELL = "TRADE_SELL"

# --- Status codes ---
STATUS_SUCCESS = "STATUS_SUCCESS"
STATUS_FAIL = "STATUS_FAIL"

# --- Candle wick types ---
CANDLE_HIGH = 1  # upper wick analysis
CANDLE_LOW = 2   # lower wick analysis

# --- Indicator computation window ---
# Max closed candles fed to one indicator computation (build_indicator_input)
# and therefore the warmup history required per TF for NaN-free indicators.
# Must stay >= the slowest indicator lookback (ema_100 needs 100).
INDICATOR_WINDOW_ROWS = 105
